### ISSUE TITLE
Specification of the Input Format for Bulk Imports

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#522] opened 2021-01-04 15:18 UTC
Specification of the Input Format for Bulk Imports
Create a JSON schema that is available for users to validate against
https://json-schema.org/ 
https://github.com/OpenConceptLab/ocldev/blob/master/ocldev/oclvalidator.py

**Comment by maurya** [comment] 2021-02-10 19:08
Pushing to next week awaiting a response from Apelon

**Comment by paynejd** [comment] 2021-07-13 15:04
This is now a duplicate of #551 - closing out

**Closed by paynejd** 2021-07-13 15:04 UTC
Labels: duplicate
