### ISSUE TITLE
Maintain Tasks in Postgres

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1777] opened 2024-02-20 12:47 UTC
Context:
Redis is a broker for Celery. The states are maintained in Redis and OCL API queries Flower for to get tasks running/pending/successful/failed. This is currently maintained for 72 hours or next deployment.

Tasks:
- [x] Postgres to be able to maintain the states of tasks. Redis + Celery stays as is.
- [x] Handle all task events, start/success/failed/retry/etc
- [x] API to get all tasks for a user
- [x] Remove Flower dependency

**Comment by snyaggarwal** [comment] 2024-03-06 04:15
@rkorytkowski @paynejd this is deployed on Dev. Please test pepfar scripts and any other manual testing on dev this week.

**Comment by paynejd** [comment] 2024-03-13 12:53
Mismatch between summaries -- see summary in this screenshot (queried directly from the API):
<img width="634" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/1189689/70549e78-2169-4600-b075-751f24dd8036">

Compare with `result.detailed_summary` in the verbose response, where it says it processed 261 out of 261:
```
Started: 2024-03-13 12:25:37.750349 | Processed: 261/261 | Created: 261 | Updated: 0 | Deleted: 0 | Existing: 0 | Permission Denied: 0 | Time: 78.23880672454834secs
```

Also worth noting that the start times are different -- I'm assuming this is not a bug, but it's also probably not ideal behavior

**Comment by paynejd** [comment] 2024-03-13 13:00
In the response in verbose mode (for a completed task), `result` should not be serialized

After unserializing `result` (e.g. `json.loads`), `result.report` is still serialized (e.g. it got serialized twice) -- this should also be unserialized

In `result.report`, the values in `child_resource_time_distribution` do not add up to the total elapsed time, which was 78 seconds -- why is there such a big difference? There are sources, collections, and versions in the import json -- should these be here as well, or are those not sent to parallel child processes?
```
'child_resource_time_distribution': {'concept': 15.847328662872314, 'mapping': 10.734777688980103, 'reference': 15.731571435928345}}
```

**Comment by paynejd** [comment] 2024-03-13 13:29
Task is displayed as "PENDING" even though it is already starting to be processed:
<img width="744" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/1189689/d7991b44-33c3-48f9-b045-842c505b556d">

**Comment by paynejd** [comment] 2024-03-13 13:55
I ran a second import, and there is a big mismatch in the counts:
<img width="692" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/1189689/e50c133f-108f-43b3-872c-a5cb17ab24bb">

And there is a big difference between the numbers shown in this image and in the `result.report` field in the response:
```
{'total': 539, 'processed': 539, 'created': 539, 'updated': 0, 'invalid': 0, 'exists': 0, 'failed': 0, 'exception': 0, 'deleted': 0, 'others': 0, 'unknown': 0, 'permission_denied': 0, 'elapsed_seconds': 129.78452610969543, 'start_time': '2024-03-13 13:27:32.889688', 'child_resource_time_distribution': {'concept': 10.199201822280884, 'mapping': 30.620508670806885, 'reference': 35.50830268859863}}
```

**Comment by paynejd** [comment] 2024-03-15 16:10
This is fixed:
- [x] No longer experiencing an issue retrieving the task ID when submitting a new bulk import

Three issues:
- [ ] `response.result` is still serialized -- I think we would prefer for this data to be returned simply as JSON (rather than serialized)?
- [ ] Import status shown as `PENDING` even though processing is already underway (this happened with both of my round 2 imports):
<img width="657" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/1189689/7327e64a-03df-41f4-bf6c-cab62511f7d5">

- [ ] Mismatch between counts, the total number processed, etc. -- in my first (smaller) import, this worked perfectly; in my second (larger) import, the counts did not match up (see only 540 processed in the result.report and 575 in the parent task, out of a total of 654 resources in the import script):
```
\"detailed_summary\": \"Started: 2024-03-15 15:56:09.509480 | Processed: 540/540 | Created: 539 | Updated: 0 | Deleted: 1 | Existing: 0 | Permission Denied: 0 | Time: 138.3544499874115secs\", \"report\": {\"total\": 540, \"processed\": 540, \"created\": 539, \"updated\": 0, \"invalid\": 0, \"exists\": 0, \"failed\": 0, \"exception\": 0, \"deleted\": 1, \"others\": 0, \"unknown\": 0, \"permission_denied\": 0, \"elapsed_seconds\": 138.3544499874115, \"start_time\": \"2024-03-15 15:56:09.509480\", \"child_resource_time_distribution\": {\"concept\": 10.30651330947876, \"mapping\": 20.206477403640747, \"reference\": 30.55776309967041}
```
<img width="627" alt="image" src="https://github.com/OpenConceptLab/ocl_issues/assets/1189689/11607fe4-f2ff-43e1-a798-79f1c599108a">

**Comment by snyaggarwal** [comment] 2024-04-03 06:48
@paynejd Serialization is fixed and its deployed on QA and Staging

**Comment by paynejd** [comment] 2024-04-03 11:48
I tested serialization on dev and it's working well! Anything else to do on this ticket before we close it out?

**Comment by snyaggarwal** [comment] 2024-04-04 05:43
@paynejd This is fixed on Staging now.

**Comment by paynejd** [comment] 2024-04-04 13:00
Round 2 of tests in staging worked flawlessly!

Only remaining step: Test out the subscription module in staging.

**Comment by snyaggarwal** [comment] 2024-04-29 07:39
@rkorytkowski @paynejd Added a job to expire (remove) tasks from postgres when its older than a week.

**Closed** 2024-06-06 02:29 UTC
Labels: type/feature, component/api
