### ISSUE TITLE
Optimize ranking of search results

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#512] opened 2020-12-17 13:16 UTC
The weighting of search results may need to be modified. 2 examples in global search:
“English” is an exact match for a preferred concept name, yet shows up low in the search results
“Eng” is an exact match for a concept ID, yet does not show up anywhere in the first page of results

How are results currently ranked and what options do we have for optoimizing?  Let's discuss on our upcoming architecture call

**Comment by snyaggarwal** [comment] 2021-05-04 09:41
@paynejd is this duplicate of #649? If yes, then can we close this?

**Closed** 2023-07-05 20:20 UTC
Labels: duplicate
