### ISSUE TITLE
Upgrade OCL Online to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1470] opened 2023-02-07 13:45 UTC
Older google analytics tokens will be disabled on July 1, 2023.

We also want to delete any unused google analytics properties

**Comment by snyaggarwal** [comment] 2023-08-30 11:27
@paynejd This is duplicate of #1600, moving this to the same status. Please move it back if its different.

**Closed** 2023-09-29 12:07 UTC
Labels: duplicate
