### ISSUE TITLE
Create OCL infrastructure ansible scripts for AWS in new ocl infrastructure repo

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#325] opened 2020-09-10 13:42 UTC
- [X] Give ocl admin team access to `ocl_infrastructure` repo (Jon)
- [X] Create OCL admin AWS account (Jon)
- [ ] Write OCL infrastructure Ansible scripts (Sunny)

**Comment by paynejd** [comment] 2020-09-10 14:11
@snyaggarwal You now have access to the `ocl_infrastructure` repo and I sent credentials to sign into AWS account via Slack. Please let me know if anything else needed to support this process.

**Comment by aprilcurrier** [comment] 2020-10-05 12:36
Duplicate of AWS work being completed by Rafal

**Closed by aprilcurrier** 2020-10-05 12:36 UTC
