### ISSUE TITLE
Create a new public OCL roadmap

### ISSUE THREAD

**Issue by maurya** [OpenConceptLab/ocl_issues#158] opened 2019-09-25 15:12 UTC
This will be the Roadmap for OCL 2020 Direction and plan 

- [x] Get Previous 3 roadmaps from @paynejd 
2019 roadmap: https://drive.google.com/open?id=1uANoSmEeeiho64oMCZ6TH1uFuQ6njjHLJPeQhO6AhHQ
2018 roadmap: https://drive.google.com/open?id=1SU1WT6sbbdCFfHv-ShgkyuXcbCC6Jmu4n-XZQ-kPPD4
2017 roadmap: https://drive.google.com/open?id=1OQEyCwAU7l5y_4TM0VMZskIKaV0U44mRpemJ0AJYF_g
2016 roadmap: https://drive.google.com/open?id=1lAg_FFa1rjL1d9NxZWQHetV7xQVA-VudK1R6kpVdBvs
2015 roadmap: https://drive.google.com/open?id=183JJ-5WHRXonbxQAyCMOSb-svdA1w6hTCvyousfIgOs
- [x] divide the roadmap by product -4-8 product - Started working - https://docs.google.com/document/d/12IAJKHyec7yO5TYDKcNguWsyGHMV_yQLCs3rglsgn-Q/edit#
    - [x] MSP- OCL metadata browser
    - [x] OCL-Core- OCL-TS
    - [x] OCL-Web-  Authoring interface - We based CSV import tool
    - [x] OCL-OMRS - authoring interface
    - [x] Subscription module - for OpenMRS - omod
    - [x] Mobile browser -Android prototype - offline capabilities 
    - [x] ETL environment - IMAP services OCL providing integration layer 
    - [x] OCL-dev - Python development library
    - [x] Metadata Clearing House - Providing content in OCL - Publishing ICD-10, 11 and Loinc and automating - keeping those things updating in OCL
- [ ] Consolidate agreements with PEPFAR
- [ ] Consolidate Security Audit Feature Requirements
- [ ] Consolidate Permissions Infrastructure Requirements
- [ ] Consolidate Maturity models from digital square and Dial 
- [ ] Consolidate GitHub tickets

**Comment by paynejd** [comment] 2020-09-10 19:34
See #304 in ocl_issues.

Also see DATIM-OCL/316

**Comment by paynejd** [comment] 2020-10-05 12:22
This is an older ticket that is a duplicate of #388 -- closing this out

**Closed by paynejd** 2020-10-05 12:22 UTC
Labels: documentation, duplicate
