### ISSUE TITLE
Full support for OCL-OMRS Subscription Module

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#43] opened 2018-02-28 18:27 UTC
This is nearly done, but needs to be tested

**Comment by rkorytkowski** [comment] 2018-03-12 14:51
Hey @paynejd, would you oppose including retired concepts/mappings in full exports of sources/collections? The thing is that we need to somehow retire them on the OpenMRS side when they are retired in OCL. Since they are currently simply excluded from exports, we have to use a post-processing on the OpenMRS side to discover concepts missing in exports and retire them. I also noticed some mappings, which reference both retired and non-retired concepts and this causes mappings not to be imported due to the lack of retired concepts. In my opinion the cleanest approach would be to include all concepts in exports regardless of the retire flag.

**Comment by paynejd** [comment] 2018-03-12 14:54
I actually thought that retired concepts and mappings were always included
in exports! Yes, you can definitely make that the default behavior, and
then we can decide in the future if we want to also allow creation of
custom exports that do not contain retired resources.

**Comment by rkorytkowski** [comment] 2018-03-13 13:15
Addressed in https://github.com/OpenConceptLab/ocl_issues/issues/49

**Comment by rkorytkowski** [comment] 2018-03-15 14:31
So this time the import of CIEL v2017-11-18-test3 into OpenMRS went well. It took 3 hours 9 minutes 36 seconds. There were 53 errors, 212269 added items, 2723 updated items. The errors were caused by duplicate concept names in the same concept e.g. 163656AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA has names Koulè orange and koulè Orange (equal, but different case) and related mappings. I'll see if they got fixed in the latest version of CIEL i.e. 20180223, which I'm loading now.

Unfortunately, there's some regression in import performance on staging and it's super slow. I'll see if #47 has something to to with it. I can easily test that as the change hasn't been deployed to production yet. I will try importing there.

**Comment by rkorytkowski** [comment] 2018-03-16 12:47
The import into staging wasn't that bad after all and completed by the next day... It was much faster on production though... If #47 will slow down the next import on production, then it would be good to either revert or see why it's not efficient for bulk import. I'll leave it as is now.

I'm importing CIEL 20180223 into OpenMRS...

**Comment by rkorytkowski** [comment] 2018-03-16 12:49
Documented importing CIEL at https://github.com/OpenConceptLab/oclapi#importing-ciel-to-staging-and-production

**Comment by rkorytkowski** [comment] 2018-03-19 12:01
So the import into OpenMRS of CIEL 20180223 on top of 20171118 went well and it took 1 h 3 minutes. The same errors were reported. I'll send a note to Andy to fix issues with a next release. I'll release the openconceptlab module with fixes now and consider the issue completed.

**Comment by rkorytkowski** [comment] 2018-03-19 12:58
Released the openconceptlab module 1.2.3.

**Closed** 2018-08-09 08:31 UTC
