### ISSUE TITLE
Upgrade Postgres to latest stable (14.4)

### ISSUE THREAD

**Issue by snyaggarwal** [OpenConceptLab/ocl_issues#1288] opened 2022-05-05 07:06 UTC
- [x] Move Local development and Bamboo CI to postgres 14.4 (dockerfile)
- [x] Move QA environment to postgres 13.7 and 14.4
- [x] Move Staging environment to postgres 13.7 and 14.4
- [x] Move all other environments to postgres 13.7 and 14.4
- [x] Move Production environment to postgres 13.7 and 14.4

**Comment by rkorytkowski** [comment] 2022-10-07 10:20
The latest available version on RDS is 13.7. I will downgrade local version to 13.7 and upgrade QA.

**Comment by rkorytkowski** [comment] 2022-10-07 11:31
I did further reading and it is actually possible to upgrade to 14.3, but it's a 2 step upgrade. First we need to upgrade to 13.x and then to 14.3. Let's upgrade to 14.3 then...

**Comment by rkorytkowski** [comment] 2022-10-18 12:37
Currently hitting an issue with oclapi on staging not being able to access DB through pgbouncer, but working when accessing DB directly. The issue is only to be observed on staging.

The issue is not present on other envs upgraded to 14.4 (qa, dev, demo, who-staging).

Production DB upgrade is on hold until staging is fixed.

**Comment by rkorytkowski** [comment] 2022-10-19 11:16
Staging is now fixed. It was an issue with PG bouncer not having big enough pool for the new session mode setting.

**Comment by rkorytkowski** [comment] 2022-10-20 10:17
Done!

**Closed** 2022-10-20 10:17 UTC
Labels: infra
