### ISSUE TITLE
Updated concepts removed from prior source versions

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#185] opened 2019-12-06 16:44 UTC
When a concept is updated, the replaced concept version is removed from existing source versions. Example process:

1. Create a new org & source
2. Create concept "123" (let's call this 123-alpha)
3. Create source version "v1.0"
4. Update concept "123" (let's call this 123-beta)
5. Create new source version "v1.1"

The concept "123-beta" is can be retrieved (correctly) from source version "v1.1" and HEAD. However, concept "123-alpha" should be in source version v1.0, but it is no where to be found.

I have a test batch that I am trying to run that I'll email you so that you can reproduce the error.

**Comment by rkorytkowski** [comment] 2020-01-06 12:43
I was able to reproduce it and working on a fix.

**Comment by rkorytkowski** [comment] 2020-01-08 14:13
Committed a fix, but we are awaiting deployment to QA and other envs. We have some issue with CI at https://ci.openmrs.org/browse/OCL-OA-290 I'll reach out to IT for help.

**Comment by rkorytkowski** [comment] 2020-01-09 14:50
Deployed to qa and staging.

**Comment by paynejd** [comment] 2020-01-13 12:15
The issue is resolved on staging -- thank you! Has the index been rebuilt
on other environments?

**Comment by rkorytkowski** [comment] 2020-01-13 12:22
The fix has been deployed to qa and staging. Indexes have been rebuilt there.

I can push to production and demo, but please let me know, if there are any work underway, because we may be down for a few hours. Would tomorrow 4 am - 8 am GMT-5 work?

**Comment by rkorytkowski** [comment] 2020-01-14 14:41
@paynejd, do let me know, if we can upgrade production any day this week.

**Comment by paynejd** [comment] 2020-01-15 03:26
Yes let's upgrade production and demo during the east African night. Thank
you!

**Comment by rkorytkowski** [comment] 2020-01-15 09:59
@paynejd, okay. I'll do it tomorrow (Jan, 16th) from 9 to 11 pm UTC+3 (EAT).

**Comment by rkorytkowski** [comment] 2020-01-17 07:35
Demo and Production have been upgraded.

**Closed** 2020-04-30 17:25 UTC
Labels: blocker, bug, top-priority
