### ISSUE TITLE
Add all cascade input params into Operations panel

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1454] opened 2022-12-22 17:17 UTC
We want the Operations panel to be where we go to test cascade, including the new parameters added for cloning (`omitIfExistsIn` and `equivalencyMapType`). Let's add all of the cascade input options into the operations panel

**Comment by snyaggarwal** [comment] 2023-01-05 04:22
this is deployed on QA (except omitIfExistsIn)

**Comment by jamlung-ri** [comment] 2023-01-05 13:47
@snyaggarwal Thanks for doing this. I am trying this out, and things are generally working well. I can perform cascade operations on a concept using any Server Base URL, and the cascade parameters are able to be adjusted to change the API call being made. 

I'm noticing a couple of things:

- [ ] Obviously this will need OmitIfExistsIn once it's ready (#1451) 
- [ ] The "Open in New Window" and "Copy URL" buttons seem to not be updating with the cascade input parameters. I attempted to use the operations panel to do a cascade operation, and it did the correct thing in the Response window ([link to correct API call](https://api.qa.openconceptlab.org/users/ocladmin/sources/CascadeTest/concepts/AA/$cascade/?method=sourcetoconcepts&mapTypes=&excludeMapTypes=&returnMapTypes=*&cascadeHierarchy=true&cascadeMappings=true&includeRetired=false&cascadeLevels=*&reverse=false&view=hierarchy)), but those two buttons still outputted the [basic cascade API call](https://api.qa.openconceptlab.org/users/ocladmin/sources/CascadeTest/concepts/AA/$cascade/).

**Comment by snyaggarwal** [comment] 2023-01-06 04:43
@jamlung-ri Fixed the Copy URL and New Tab redirection

**Comment by jamlung-ri** [comment] 2023-01-09 19:16
Now that OmitsIfExistsIn is in there, I think this is fine to deploy for now.

**Comment by jamlung-ri** [comment] 2023-01-09 19:26
A new recent issue came up, actually. Very recently i.e. within the past few hours, the Operations panel seems to be failing for me. Might just be my browser though. I can open the panel and fill out info, but when I click Execute, it just gets stuck here and gives me these errors.

![image](https://user-images.githubusercontent.com/55999682/211391201-e647d61c-3291-4f05-863b-48ed982a00e8.png)

**Comment by snyaggarwal** [comment] 2023-01-10 06:09
@jamlung-ri I wasn't able to reproduce this and interestingly no errbits were raised. Could you retry after refresh?

**Comment by jamlung-ri** [comment] 2023-01-10 14:15
I tried a full refresh and also used other browsers, and I'm still getting the same error when I click the Execute button. That said, I know that sometimes it's just my browser that is the problem, so if this isn't an issue for anyone else, then we can disregard.

> react-dom.production.min.js:101 Uncaught TypeError: Cannot read properties of null (reading 'version_url')
    at onClick (OperationsDrawer.jsx:207:47)
    at Object.We (react-dom.production.min.js:52:317)
    at Ke (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Nr (react-dom.production.min.js:100:68)
    at Pr (react-dom.production.min.js:101:380)
    at react-dom.production.min.js:113:65
    at De (react-dom.production.min.js:292:189)
    at react-dom.production.min.js:50:57
    at Rr (react-dom.production.min.js:105:469)
onClick @ OperationsDrawer.jsx:207
We @ react-dom.production.min.js:52
Ke @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Nr @ react-dom.production.min.js:100
Pr @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
De @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
Rr @ react-dom.production.min.js:105
Gt @ react-dom.production.min.js:75
Xt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Hl @ react-dom.production.min.js:122
Fe @ react-dom.production.min.js:292
Yt @ react-dom.production.min.js:73

**Comment by jamlung-ri** [comment] 2023-01-12 14:52
@snyaggarwal FYI this is working again for me. I also have been using both parameters from #1451, so it seems to me that this ticket can be closed.

**Comment by snyaggarwal** [comment] 2023-01-24 11:17
@jamlung-ri @paynejd This is deployed on production. Closing this.

**Closed by snyaggarwal** 2023-01-24 11:17 UTC
Labels: web2
