### ISSUE TITLE
API Button at the Bottom Right - Link to Swagger

### ISSUE THREAD

**Issue by jamlung-ri** [OpenConceptLab/ocl_issues#1173] opened 2022-01-05 13:15 UTC
We had some suggest that the API version button (see below) should link to the Swagger page for that environment.

![image.png](https://images.zenhubusercontent.com/5df114a3d094b314eeec671c/2ff8d79a-8292-4f38-8b57-683a53bd93d4)

**Comment by snyaggarwal** [comment] 2022-01-06 08:53
@jamlung-ri this is duplicate of #1174

**Closed** 2022-01-06 12:55 UTC
Labels: duplicate
