### ISSUE TITLE
Change OCL SSO/KeyCloak favicon

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1651] opened 2023-08-17 18:32 UTC
Please change the favicon for OCL SSO/KeyCloak to match the favicon used for the TermBrowser.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdVFVIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--59ddfd4c375bb145bd28aff8c9b6241c3b1b7cce/image.png)

**Comment by snyaggarwal** [comment] 2024-03-12 11:29
This is duplicate of #1774

**Closed by snyaggarwal** 2024-03-12 11:29 UTC
