### ISSUE TITLE
Implement Advanced Add References panel

### ISSUE THREAD

**Issue by paulsonder** [OpenConceptLab/ocl_issues#1378] opened 2022-10-11 09:51 UTC

**Comment by jamlung-ri** [comment] 2022-10-12 14:29
Braindump for OpenMRS' cascade needs:
* User quote (Casey from OpenELIS): "I want to add a lab set (panel), all the associated tests with the panel, and the coded responses to those tests" (see visual below for the intended concepts to be added)
   * Example panel: [Coombs' test](https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/161499/) - contains two lab tests ([Direct Coombs test](https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/159607/) and [Indirect Coombs test](https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/159606/)) - both tests have the results [Positive](https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/703/) and [Negative](https://app.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/664/)
   * Intended behavior: If a user selects the Labset panel from the CIEL source, then clicks "Add to Collection", the user should be able to leverage a $cascade window/modal to specify options to get all the intended concepts/mappings. See the visual below for the concepts that should be added. For each concept, there are certain mapping that should also be included, based on their map-type.
   * $cascade parameters required: 
       * MapTypes: CONCEPT-SET, Q-AND-A, SAME-AS (note that the first two mappings get you to the intended concepts to be added, while the SAME-AS mappings are simply mappings that should also be included for any concepts that actually are added to the collection)
       * Levels: All (in the end, 3 cascade levels are required to get to all the intended concepts/mappings.  
   * Visual of labset concepts (this window is currently filtering for map types `CONCEPT-SET,Q-AND-A`): 
![image](https://user-images.githubusercontent.com/55999682/195368387-8da2e694-9e52-4f06-b194-c1bf4f19fb28.png)

**Comment by jamlung-ri** [comment] 2022-10-13 13:59
Slightly unrelated to this ticket but still important is the ability to see what concepts and mappings are getting added when using this feature. A "results list" would really help users, especially if they could select concepts/mappings to exclude from that list.

**Comment by jamlung-ri** [comment] 2022-10-14 14:21
Some requirements and behaviors for this are in the brainstorming stage. Jon and I are thinking through it [here](https://docs.google.com/document/d/135GycK_fkNna0NHw85DKf0hkLjk-UU5a5BT1Gdh47xg/edit#heading=h.b7w61dhww179), but we'll come back with more formal requirements when we're more ready.

**Comment by jamlung-ri** [comment] 2022-10-17 12:07
Copying details from https://github.com/OpenConceptLab/ocl_issues/issues/1131

> A potentially useful lo-fi drawing for a $cascade results panel: https://docs.google.com/drawings/d/19slrFyJebEKwDSve65V4tzAqKthrbA-uiP9V8vRWMcg/edit
>
> Edit: This cascade drawing is missing some key generic functionality, particularly for controlling the number of levels down you can go and the map types that you might want to be including.
>
> In terms of behavior, we will need to perform $cascade request when the user is on the dialog and switching between options of the cascade. Should we disable the button to add until the results of the cascade are not displayed?
> 
> Makes sense that the $cascade request will occur as the user clicks the option, so there will likely be some delay as the API returns results (especially if it's a large set of results). Because of the risk for delay, I don't really want to disable the Add button, but we should at least show that the results are still loading. The user can decide if they do or don't want to wait and review the results before clicking the Add button.

**Comment by jamlung-ri** [comment] 2022-10-19 12:36
First step: @jamlung-ri and @paynejd to scope this out in this ticket

**Comment by paynejd** [comment] 2022-11-01 14:07
Starting to design this here:
https://docs.google.com/presentation/d/1Qo8bE7g-UhGNGKxqOCcL3patAxaEblh81FA4gWlsLBM/edit#slide=id.p

**Comment by jamlung-ri** [comment] 2022-11-02 12:25
This sprint: We need to scope out this work. What are we going to be tackling? What will be push out to a later date?

**Comment by paynejd** [comment] 2022-12-20 15:06
Since we already added support for the OpenMRS-cascade into TB, changing the name of this ticket to "Implement Advanced Add References panel" (also closing out #1201)

High-level requirements brought over from #1201:
1. List/confirm references to be added
2. Optionally expand a reference to display results inline i.e. Preview window?
3. Expose cascade parameters - filter map types, number of levels, hierarchy, etc.
4. Provide options on what to store – dynamic reference vs. evaluated resources, versioned/versionless, etc.
5. ability to transform to versioned references might be an immediate requirement for the OpenMRS community

**Comment by jamlung-ri** [comment] 2024-03-15 18:48
Closing out this epic since we will be tackling most of this in an upcoming OCLv3 epic for repository management. Documentation for this will live in this document: https://docs.google.com/document/d/1nkSEU4qizs3fk6y8DZ_p_ZP3-8MA2ovgup3b22L5Bn4/edit#heading=h.zbg0nbu53vfv

**Closed by jamlung-ri** 2024-03-15 18:48 UTC
Labels: Design, V3
