### ISSUE TITLE
Resolve data corruption issue experienced on staging

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#243] opened 2020-06-09 15:26 UTC
A data corruption issue occurred on staging OCLAPI when the new custom attribute filter functionality was deployed and the data integrity script was run that automatically deletes broken references. Staging data is now in a good state (meaning no broken references), but we decided to not restore a database backup because only MSP metadata experienced any data corruption and we are planning to import the updated set of metadata later this week. It appears that the data corruption issue occurred when deleting organizations and repositories and then following that up by running the data integrity script that deletes broken references.

2 areas of work to resolve this:
- [x] Fix the code for dropping organizations and repositories to eliminate data corruption issues
- [x] Refine data integrity scripts - specific changes to be defined

@rkorytkowski Please provide a detailed description of the issues identified and the solutions put into place.

**Comment by rkorytkowski** [comment] 2020-06-10 09:07
Currently, when dropping an organization, not all underlying resources are deleted, thus we end up with some resources without a parent resource e.g. collection_mapping, collection_concept and a few others. When we try to index such resources for full text search, the index process fails reporting broken references, thus we need to clean them up. The fix for dropping an org needs to go in https://github.com/OpenConceptLab/oclapi/blob/master/ocl/oclapi/rawqueries.py#L46

To remedy the situation and fix broken references, we have an endpoint, which scans the DB and checks if all resources have valid references. If it finds any broken references, they are reported and it is possible to automatically delete them. The process was ran by me before re-indexing and it reported a number of broken references. It was supposed to clean them up automatically by deleting only broken references, however it apparently has some bug, which incorrectly deleted some valid resources. It is yet to be determined where the bug is. However, the issue is clearly isolated to occur only during the data integrity check and deletion of broken references.

Addressing these 2 issues should prevent the situation from happening again. In the future more care needs to be taken into account when resolving data integrity issues. The list of resources to be deleted needs to be precisely analysed before running the deletion.

Data integrity issues can be discovered by running data integrity checks, which currently can be executed manually as per https://github.com/OpenConceptLab/oclapi/wiki/Data-integrity-checks. My recommendation is to setup a CI plan to run the check periodically and fail if any issues occur so a bug can be discovered and addressed quickly.

We do take backups every 24h to mitigate any data loss. They can be restored fully or partially (manually). It is possible to manually isolate what's missing and restore only what's missing by running direct mongodb queries.

**Comment by rkorytkowski** [comment] 2020-06-10 09:36
Also another note on that is we'll be migrating to PostgreSQL in the next 3-4 months, which has foreign keys and completely eliminate the risk of having bad references.

**Comment by aprilcurrier** [comment] 2020-06-25 13:09
Still in progress. Fixing the delete method as a first step.  Anticipated completion of 6/26. 
 Est 40% complete as of rollover

**Comment by aprilcurrier** [comment] 2020-06-25 13:10
@rkorytkowski  to describe solution in ticket

**Comment by paynejd** [comment] 2020-07-01 16:41
@rkorytkowski Please provide update on the approach and progress here -- thank you!

**Comment by rkorytkowski** [comment] 2020-07-03 15:16
I've fixed the delete operations on org, source and collection models which were the reason we were hitting data integrity issues. We were not deleting CollectionConcept and CollectionMapping when deleting collections and membership of users in orgs for deleted orgs.

I'll be examining the data integrity checks and automated resolution algorithm to fix the deletion of incorrect items.

I'll also add a check on CI to run data integrity checks on staging and production every 24h and fail, if we find any issues to be notified right away.

**Comment by rkorytkowski** [comment] 2020-07-06 13:54
Regarding refining data integrity checks. I've found already one bug, which was responsible for the lost of data when applying fixes on broken references found by the data integrity checks. 

If an item had broken references on a list field, it deleted the item, instead of deleting a broken reference from the list. It means that a concept version was deleted, if it was included in a non existing source version, instead of deleting that reference to a non existing source version.

I'm working on a fix and test cases to document it.

I'll be examining the broken references resolution code further. Until we make sure all is fixed we will not be fixing any broken references.

**Comment by paynejd** [comment] 2020-07-06 15:25
Tested org deletion on staging and the while the data is being deleted, the API is still returning null records for any orgs that were deleted. See this query returns 48 records and that many of them are blanked out (note that these orgs are private, so you'll need to use superuser token):
```
https://api.staging.openconceptlab.org/orgs/?q=DATIM&limit=100&verbose=true
```
Here's an example of one of the blanked out records:
```
    {
        "type": "",
        "uuid": "",
        "id": "",
        "public_access": "",
        "name": "",
        "company": "",
        "website": "",
        "location": "",
        "members": "",
        "public_collections": "",
        "public_sources": "",
        "created_on": null,
        "updated_on": null,
        "created_by": "",
        "updated_by": "",
        "url": "",
        "members_url": "",
        "sources_url": "",
        "collections_url": "",
        "extras": ""
    },
```

**Comment by aprilcurrier** [comment] 2020-07-10 17:26
Need more fixes on this. Is a blocker for Prod deployment 50% complete upon rollover

**Comment by rkorytkowski** [comment] 2020-07-20 13:10
All fixes have been applied in code. I've also ran the changes against a backup taken from the staging environment.  The broken references from previous deletions were correctly resolved without excessive deletions. The deletion of an org was complete and did not result in any broken references.

The change is scheduled to be pushed to staging and production tomorrow at 9 am UTC+2. There will be 5 minutes downtime. The index will have to rebuilt, which may take up to an hour for each environment and search results may be incomplete during that time.

**Comment by paynejd** [comment] 2020-07-20 13:49
Awesome thank you Rafal!

**Comment by paynejd** [comment] 2020-07-21 13:54
@rkorytkowski Can you confirm that deployment of #243 to production completes the development work related to data corruption? Do we need to create additional tickets to address this?

**Comment by rkorytkowski** [comment] 2020-07-22 10:34
It's been deployed to staging and production. It does complete the work related to data corruption. No other follow up issues needed.

**Closed** 2020-07-22 10:36 UTC
Labels: blocker, bug, top-priority
