### ISSUE TITLE
Allow any character for concept ID

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#739] opened 2021-05-05 18:23 UTC
OCL needs to allow basically any character for a concept ID. See example below of the use of a forward slash in an ID, which we'll need to handle as a special case. There may be other characters that need to get handled as a special case as well. Note that FHIR allows any character whatsoever in a code, except for leading/trailing whitespace.

It turns out there are fourteen PIH concepts that contain one or more forward slashes (/) in the concept's code, which leads to to_concept_url properties like "/orgs/PIH/sources/PIH/concepts/HOUSEWORK/FIELDWORK/". OCL only uses the code up to the first forward slash. For example, Housework/Fieldwork (273) is mapped to "HOUSEWORK" instead of "HOUSEWORK/FIELDWORK".

@Jon – I assume the OCL API and any clients using it should probably URL encode forward slashes, so HOUSEWORK/FIELDWORK would become HOUSEWORK%2FFIELDWORK within a URL, right?

HOUSEWORK/FIELDWORK
Daytime asthma symptoms for more than a few minutes more than once/week
Insulin 70/30
Radiology images of musculoskeletal system (non-cranial/spinal)
ABSENCE OF S3/S4 MURMUR
Unplanned intubation for respiratory/cardiac failure
Obstetrics/Gynecology
Dirty/Infected
Clean/Contaminated
YES, AFTER EDUCATION AND/OR ASSIGNING A COMMUNITY HEALTH WORKER
2S+RHEZ / 1RHEZ / 5RH+E
2RHZ / 4RH
2RHEZ / 4RH
Malaria in Mother Complicating Pregnancy, Childbirth and/or Puerperium

**Comment by snyaggarwal** [comment] 2021-05-06 06:16
@paynejd is this duplicate of #737? If yes, can we merge these two?

**Closed** 2021-05-07 14:26 UTC
