### ISSUE TITLE
Move concept/mapping custom attributes into details section

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1001] opened 2021-09-28 13:52 UTC
See mockup here: 
![image.png](https://images.zenhubusercontent.com/5981a15ff8b79f8376e1a78e/77ca1eff-d6c6-427e-a299-ca77df7bd7e2)

**Comment by snyaggarwal** [comment] 2021-09-29 11:09
@jamlung-ri is this duplicate of #999 ?

**Comment by jamlung-ri** [comment] 2021-09-29 12:01
Yeah it is. I went ahead and closed that duplicate out. I'll review this one later.

**Comment by jamlung-ri** [comment] 2021-09-29 15:17
This is working well in QA, including when looking at Custom Attributes of different formats. [See this as an example](https://app.qa.openconceptlab.org/#/orgs/DemoOrg/sources/MyCSVSource/concepts/Act/).

**Closed by jamlung-ri** 2021-09-29 15:17 UTC
