### ISSUE TITLE
Update mappings to use $resolveReference operation

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1714] opened 2023-12-12 13:25 UTC
Note that mappings generally do not specify a repo version and it should not resolve to a repo version unless it is explicit in the definition. Currently, $resolveReference always resolves to a specific repo version, so we may need to add a flag to optionally resolve just to a version-less repo. Let's discuss.

**Comment by snyaggarwal** [comment] 2024-03-12 11:24
@paynejd This is duplicate of #1747. Please close this if you agree

**Closed** 2024-03-12 13:06 UTC
Labels: duplicate, discussion-needed
