### ISSUE TITLE
Concept synonyms must to be included in search index

### ISSUE THREAD

**Issue by paynejd** [OpenConceptLab/ocl_issues#1219] opened 2022-02-25 14:30 UTC
It appears that synonyms may not be included in the search index. For example, search for `sgot` on production: https://app.openconceptlab.org/#/search/?q=sgot&isTable=true&isList=false&isSplit=false&page=1&exactMatch=off&type=concepts

This concept should show up high in the search results, since it has a short name that is an exact match here:
/orgs/CIEL/sources/CIEL/concepts/653/

**Comment by snyaggarwal** [comment] 2022-02-28 04:07
duplicate of #1218

**Closed** 2022-02-28 14:59 UTC
Labels: component/omrs
