### ISSUE TITLE
Duplicate mappings created during bulk import on staging, now happening on production

### ISSUE THREAD

**Issue by bmamlin** [OpenConceptLab/ocl_issues#1309] opened 2022-05-25 20:58 UTC
When importing [CIEL v2022-03-19](https://github.com/OpenConceptLab/ocl_issues/issues/1257#issuecomment-1075488390) and [CIEL v2022-05-21](https://github.com/OpenConceptLab/ocl_issues/issues/1308#issuecomment-1137793995), there are 23 duplicate mappings reappearing during the bulk import – i.e., after bulk import of a new version of CIEL and retiring any mappings that were deleted by Andy, these 23 "extra" mappings re-appear as duplicate mappings.

I don't know if it's a factor, but a common feature of these mappings is that they include a forward slash (`%2F`) in the code.

Interestingly, this is only an issue on Staging, so it can't be an issue with slashes in the codes, since those same mappings exist on Production and bulk import on Production doesn't create duplicate mappings.

**Comment by snyaggarwal** [comment] 2022-07-25 04:57
@bmamlin Can you please send me CIEL v2022-03-19  version of CIEL? I have the CIEL v2022-05-21 version.
I will try to test and hopefully reproduce this.

**Comment by bmamlin** [comment] 2022-08-04 18:28
Thanks, @snyaggarwal. You should have CIEL v2022-03-19 now (sent via Slack). I think Andy is about to release a new version of CIEL, so I may be recreating the bug again soon. 🙂

**Comment by snyaggarwal** [comment] 2022-08-05 08:59
@bmamlin Added a fix for this on Staging. Let's see with the next Staging CIEL import there shouldn't be any duplicates.

**Comment by bmamlin** [comment] 2022-08-15 15:55
Imported CIEL v2022-08-13 onto staging and ran into the problem again. Twenty-three duplicate mappings rise again:

* [CIEL 165965](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165965/) NARROWER-THAN [ICD-11-WHO RA01.1%2F1D84.Y](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2F1D84.Y/)
* [CIEL 165964](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165964/) NARROWER-THAN [ICD-11-WHO RA01.1%2FBC43.Z](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2FBC43.Z/)
* [CIEL 165958](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165958/) NARROWER-THAN [ICD-11-WHO RA01.1%2FFB32.20](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2FFB32.20/)
* [CIEL 165957](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165957/) NARROWER-THAN [ICD-11-WHO RA01.1%2FCB41.00](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2FCB41.00/)
* [CIEL 165956](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165956/) NARROWER-THAN [ICD-11-WHO RA01.1%2F1G40](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2F1G40/)
* [CIEL 165955](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165955/) NARROWER-THAN [ICD-11-WHO RA01.1%2FGB60.Z](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2FGB60.Z/)
* [CIEL 165914](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165914/) NARROWER-THAN [ICD-11-WHO RA01.1%2F1A2Y](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2F1A2Y/)
* [CIEL 165913](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165913/) NARROWER-THAN [ICD-11-WHO RA01.1%2FBD72](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2FBD72/)
* [CIEL 165906](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165906/) NARROWER-THAN [ICD-11-WHO RA01.1%2F3B64.Z](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2F3B64.Z/)
* [CIEL 165905](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165905/) NARROWER-THAN [ICD-11-WHO RA01.1%2F4B0Y](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2F4B0Y/)
* [CIEL 165897](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165897/) NARROWER-THAN [ICD-11-WHO RA01.1%2FJB63.Y](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2FJB63.Y/)
* [CIEL 165887](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165887/) NARROWER-THAN [ICD-11-WHO RA01.1%2FCA20.Z](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2FCA20.Z/)
* [CIEL 165886](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165886/) NARROWER-THAN [ICD-11-WHO RA01.1%2FAB0Z](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2FAB0Z/)
* [CIEL 165885](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165885/) NARROWER-THAN [ICD-11-WHO RA01.1%2F1A2Z](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2F1A2Z/)
* [CIEL 165884](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165884/) NARROWER-THAN [ICD-11-WHO RA01.1%2F8E47](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2F8E47/)
* [CIEL 165883](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165883/) NARROWER-THAN [ICD-11-WHO RA01.1%2FBC42.Y](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2FBC42.Y/)
* [CIEL 165869](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165869/) NARROWER-THAN [ICD-11-WHO RA01.1%2FCA42.Y](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2FCA42.Y/)
* [CIEL 165868](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165868/) NARROWER-THAN [ICD-11-WHO RA01.1%2FCA4Z](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2FCA4Z/)
* [CIEL 165867](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165867/) NARROWER-THAN [ICD-11-WHO RA01.1%2FCB00](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2FCB00/)
* [CIEL 165866](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165866/) NARROWER-THAN [ICD-11-WHO QC42%2FRA01.1](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/QC42%2FRA01.1/)
* [CIEL 165608](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165608/) NARROWER-THAN [ICD-11-WHO RA01.1%2FCA40.1Y](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2FCA40.1Y/)
* [CIEL 160009](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/160009/) SAME-AS [org.openmrs.module.mdrtb DIRECT%2FINDIRECT](https://app.staging.openconceptlab.org/#/orgs/OpenMRS/sources/org.openmrs.module.mdrtb/concepts/DIRECT%2FINDIRECT/)
* [CIEL 165633](https://app.staging.openconceptlab.org/#/orgs/CIEL/sources/CIEL/concepts/165633/) NARROWER-THAN [ICD-11-WHO RA01.1%2FCA07.0%26XN109](https://app.staging.openconceptlab.org/#/orgs/WHO/sources/ICD-11-WHO/concepts/RA01.1%2FCA07.0%26XN109/)

I'll again go through and manually retire the duplicate mappings. I still find it beyond suspicious that every single one of these has forward slash (`%2F`) in its target code.

**Comment by bmamlin** [comment] 2022-08-16 22:48
Andy made some changes and we started over as CIEL v2022-08-14. Importing on staging once again resurrected these 23 duplicate mappings and I had to retire them again.

**Comment by snyaggarwal** [comment] 2022-09-16 04:56
@bmamlin when you import the next version on staging, please don't delete the duplicate mappings. I would like to debug the difference that's creating duplicates.

**Comment by bmamlin** [comment] 2022-09-29 20:07
@snyaggarwal sure. I'll need to warn you before the next CIEL release on staging anyway, since we are now [using the OpenMRS Custom validation schema on staging](https://github.com/OpenConceptLab/ocl_issues/issues/1027#issuecomment-1217432012), which @paynejd thinks could lead to an adventure during the next release on staging. Andy is working on a new release, so expect we'll have one within the next week or so.

**Comment by bmamlin** [comment] 2022-10-16 14:25
Same problem with v2022-10-12 (#1384).

**Comment by snyaggarwal** [comment] 2022-10-16 15:04
@bmamlin please do not delete the duplicate mappings, I will debug the data tomorrow.

**Comment by askanter** [comment] 2022-10-16 15:14
Confirming none of this is actual dupes in the data that I need to fix, right?

**Comment by bmamlin** [comment] 2022-10-16 16:13
> Confirming none of this is actual dupes in the data that I need to fix, right?

Correct. These are 23 duplicates that are getting generated during the bulk import process on Staging. I have to delete them with each release on Staging.

> please do not delete the duplicate mappings, I will debug the data tomorrow.

Sure. I'll leave them for you @snyaggarwal.

**Comment by snyaggarwal** [comment] 2022-10-17 03:26
@bmamlin I have corrected the data on Staging for these 23 mappings. Retired old mappings that had bad "from_concept_code" (due to which it was not matching, and creating new, old bug). You can now go ahead and validate and create the new version.
The next version import on staging should be good.

**Comment by bmamlin** [comment] 2022-10-18 02:31
Let's leave this ticket open. Assuming we don't create dups with the next CIEL release to Staging, we can close it then.

**Comment by bmamlin** [comment] 2022-11-07 05:44
Resolved on Staging (though it looks like problem moved to [Production](https://github.com/OpenConceptLab/ocl_issues/issues/1421#issuecomment-1305112882)).

**Comment by bmamlin** [comment] 2023-02-28 21:37
Reopening this issue, since it continues to happen with each import of CIEL on production.

**Comment by bmamlin** [comment] 2023-04-06 14:06
In 2023, we continue to see the same 15 duplicate mapping happening with each CIEL release ([v2023-01-26](https://github.com/OpenConceptLab/ocl_issues/issues/1468#issuecomment-1407249792), [v2023-02-27](https://github.com/OpenConceptLab/ocl_issues/issues/1500#issuecomment-1448953596), and [v2023-04-01](https://github.com/OpenConceptLab/ocl_issues/issues/1532#issuecomment-1499116107)).

I'm guessing these mappings may have the same problem as [those identified on Staging](https://github.com/OpenConceptLab/ocl_issues/issues/1309#issuecomment-1280229155) – i.e., a bad `from_concept_code`.

**Comment by snyaggarwal** [comment] 2023-04-11 07:57
@bmamlin I have taken prod dump and ran the mappings import (from one of the older CIEL release) and was able to reproduce this. I have added a fix for this. This should get fixed in the next release.

**Comment by snyaggarwal** [comment] 2023-07-14 12:54
No duplicates in the last CIEL import. Closing this.

**Closed by snyaggarwal** 2023-07-14 12:54 UTC
Labels: bug
